#! /usr/bin/python
# memory < 10g
import psutil
import os
import sys
import signal
from datetime import datetime
for pid in psutil.pids():
    try:
        p = psutil.Process(pid)
        if int(p.memory_info()[0]) > 1073741824 * 10:
	    print datetime.now(),kill,pid,p.username(),p.cmdline()
            os.kill(pid,signal.SIGKILL)         
    except OSError:
        pass
    except:
        pass